name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Environment Variables for Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "ENV_FILE=.env.production" >> $GITHUB_ENV

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/mintalysis/public_html/mintalysis_backend/
            git stash push --include-untracked
            git pull
            git stash pop
            docker build -t mintalysis_backend:latest .
            docker stop mintalysis_backend_container || true
            docker rm mintalysis_backend_container || true
            docker run --name mintalysis_backend_container --env-file "/home/mintalysis/public_html/mintalysis_backend/.env.production" -d -p 8001:8001 mintalysis_backend:latest
            docker exec mintalysis_backend_container printenv

