name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Environment Variables for Production
        if: github.ref == 'refs/heads/main'
        run: |
          echo "ENV_FILE=.env.production" >> $GITHUB_ENV

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/***/public_html/***_backend/
            # Stash any untracked files
            git stash push --include-untracked
            git pull
            # Restore the stashed files
            git stash pop
            # Ensure the correct environment file is used for the deployment
            docker build -t ***_backend:latest .
            docker stop ***_backend_container || true
            docker rm ***_backend_container || true
            # Use the ENV_FILE environment variable to specify the path to the environment file
            docker run --name ***_backend_container --env-file $ENV_FILE -d -p 8001:8001 ***_backend:latest
